micronaut:
  application:
    name: flyway-issues

datasources:
  default:
    url: 'jdbc:h2:mem:orgdb'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:migrations
      createSchemas: false
      schemas: flyway_history_schema,test
      init-sql: create schema if not exists flyway_history_schema; create schema if not exists test;
      default-schema: flyway_history_schema

endpoints:
  flyway:
    enabled: true
    sensitive: false
